# Site owner profile
locale                   : "en-US"
site_theme               : "default"
title                    : "Yizheng Lai"
title_separator          : "-"
name                     : &name "Yizheng Lai"
description              : &description "Yizheng Lai's academic portfolio"
url                      : https://lai1z.github.io
baseurl                  : ""
repository               : "lai1z/lai1z.github.io"

# Site Author
author:
  avatar           : "profile.jpg"
  name             : "Yizheng Lai"
  pronouns         :
  bio              :
  location         : "Beijing, China"
  employer         : "Renmin University of China"
  uri              :
  email            : "15805012636@163.com"

  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  bitbucket        :
  codepen          :
  dribbble         :
  github           : "lai1z"
  kaggle           :
  stackoverflow    :

  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :
atom_feed:
  hide                   : false
  path                   :

google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
og_description           :
social:
  type                   : Person
  name                   : "Yizheng Lai"
  links:
    - "https://github.com/lai1z"

analytics:
  provider               : "false"
  google:
    tracking_id          :

include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - docker-compose.yaml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - README
  - README.md
  - tmp
  - vendor

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

